channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - pytorch=1.7.0
  - pip
  - pip:
    - astunparse==1.6.3
    - bert-score==0.3.9
    - bpemb==0.3.3
    - cachetools==4.2.1
    - cloudpickle==1.6.0
    - cycler==0.10.0
    - dataclasses==0.6
    - datasets==1.6.0
    - decorator==4.4.2
    - deprecated==1.2.12
    - dill==0.3.3
    - docopt==0.6.2
    - editdistance==0.5.3
    - entrypoints==0.3
    - flair==0.8
    - flatbuffers==1.12
    - fsspec==2021.4.0
    - ftfy==6.0.1
    - future==0.18.2
    - gast==0.4.0
    - gdown==3.12.2
    - gensim==3.8.3
    - google-auth==1.29.0
    - google-auth-oauthlib==0.4.4
    - gpytorch==1.4.1
    - grpcio==1.34.1
    - h5py==3.1.0
    - huggingface-hub==0.0.8
    - hyperopt==0.2.5
    - importlib-metadata==3.10.1
    - install==1.3.4
    - ipykernel==5.5.5
    - ipython==7.24.1
    - janome==0.4.1
    - jedi==0.18.0
    - jinja2==3.0.1
    - jiwer==2.2.0
    - keras-nightly==2.5.0.dev2021032900
    - kiwisolver==1.3.1
    - konoha==4.6.4
    - langdetect==1.0.8
    - language-tool-python==2.5.3
    - lemminflect==0.2.2
    - lru-dict==1.1.7
    - lxml==4.6.3
    - matplotlib==3.4.1
    - matplotlib-inline==0.1.2
    - more-itertools==8.7.0
    - mpld3==0.3
    - multiprocess==0.70.11.1
    - networkx==2.5.1
    - nltk==3.6.2
    - num2words==0.5.10
    - numpy==1.18.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - overrides==3.1.0
    - pandas==1.1.5
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.18
    - pyarrow==3.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - python-levenshtein==0.12.2
    - pytz==2021.1
    - pyzmq==22.1.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scikit-learn==0.24.1
    - scipy==1.4.1
    - seaborn==0.11.1
    - segtok==1.5.10
    - sentence-transformers==1.2.0
    - sentencepiece==0.1.95
    - sklearn==0.0
    - smart-open==5.0.0
    - sqlitedict==1.7.0
    - tabulate==0.8.9
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.0
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.5.0
    - tensorflow-estimator==2.5.0
    - tensorflow-hub==0.12.0
    - tensorflow-text==2.5.0
    - termcolor==1.1.0
    - terminado==0.10.0
    - terminaltables==3.1.0
    - testpath==0.5.0
    - textattack==0.3.3
    - threadpoolctl==2.1.0
    - tqdm==4.49.0
    - typing-extensions==3.7.4.3
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - word2number==1.1
    - xxhash==2.0.2
    - _libgcc_mutex=0.1
    - _openmp_mutex=4.5
    - _tflow_select=2.3.0
    - absl-py=0.12.0
    - argon2-cffi=20.1.0
    - asn1crypto=1.4.0
    - astor=0.8.1
    - async_generator=1.10
    - attrs=21.2.0
    - backcall=0.2.0
    - blas=1.0
    - bleach=3.3.0
    - brotlipy=0.7.0
    - bzip2=1.0.8
    - c-ares=1.17.1
    - ca-certificates=2021.10.8
    - cached-property=1.5.2
    - cached_property=1.5.2
    - catalogue=2.0.4
    - certifi=2021.10.8
    - cffi=1.14.0
    - chardet=4.0.0
    - click=7.1.2
    - colorama=0.4.4
    - cryptography=2.3.1
    - cudatoolkit=10.2.89
    - cupy=9.2.0
    - cymem=2.0.5
    - cython-blis=0.7.4
    - dbus=1.13.18
    - defusedxml=0.7.1
    - expat=2.4.1
    - fastrlock=0.6
    - ffmpeg=4.2.2
    - filelock=3.0.12
    - fontconfig=2.13.1
    - freetype=2.10.4
    - glib=2.63.1
    - gmp=6.2.1
    - gnutls=3.6.15
    - google-pasta=0.2.0
    - gst-plugins-base=1.14.0
    - gstreamer=1.14.0
    - hdf5=1.10.6
    - icu=58.2
    - idna=2.10
    - importlib_metadata=3.10.0
    - intel-openmp=2020.2
    - ipython_genutils=0.2.0
    - ipywidgets=7.6.3
    - joblib=1.0.1
    - jpeg=9b
    - jsonschema=3.2.0
    - jupyter=1.0.0
    - jupyter_client=6.1.12
    - jupyter_console=6.4.0
    - jupyter_core=4.7.1
    - jupyterlab_pygments=0.1.2
    - jupyterlab_widgets=1.0.0
    - keras-applications=1.0.8
    - keras-preprocessing=1.1.2
    - lame=3.100
    - lcms2=2.12
    - libedit=3.1.20210216
    - libffi=3.2.1
    - libgcc-ng=9.3.0
    - libgfortran-ng=7.3.0
    - libgomp=9.3.0
    - libidn2=2.3.0
    - libopus=1.3.1
    - libpng=1.6.37
    - libprotobuf=3.14.0
    - libsodium=1.0.18
    - libstdcxx-ng=11.1.0
    - libtasn1=4.16.0
    - libtiff=4.1.0
    - libunistring=0.9.10
    - libuuid=1.0.3
    - libuv=1.40.0
    - libvpx=1.7.0
    - libxcb=1.14
    - libxml2=2.9.10
    - lz4-c=1.9.3
    - markdown=3.3.4
    - markupsafe=2.0.1
    - mistune=0.8.4
    - mkl=2020.2
    - mkl-service=2.3.0
    - mkl_fft=1.3.0
    - mkl_random=1.1.1
    - murmurhash=1.0.5
    - nbclient=0.5.3
    - nbconvert=6.0.7
    - nbformat=5.1.3
    - ncurses=6.2
    - nest-asyncio=1.5.1
    - nettle=3.7.2
    - ninja=1.10.2
    - notebook=6.4.0
    - numpy-base=1.19.2
    - olefile=0.46
    - openh264=2.1.0
    - openssl=1.0.2u
    - opt_einsum=3.1.0
    - packaging=20.9
    - pandoc=2.12
    - pandocfilters=1.4.3
    - parso=0.8.2
    - pathy=0.6.0
    - patsy=0.5.2
    - pcre=8.44
    - pexpect=4.8.0
    - pickleshare=0.7.5
    - pillow=8.2.0
    - pip=21.0.1
    - preshed=3.0.5
    - prometheus_client=0.10.1
    - prompt_toolkit=3.0.17
    - protobuf=3.14.0
    - ptyprocess=0.7.0
    - pycparser=2.20
    - pydantic=1.8.2
    - pygments=2.9.0
    - pyopenssl=19.0.0
    - pyparsing=2.4.7
    - pyqt=5.9.2
    - pyrsistent=0.17.3
    - pysocks=1.7.1
    - python=3.7.0
    - python-dateutil=2.8.1
    - python_abi=3.7
    - qt=5.9.6
    - qtconsole=5.0.3
    - qtpy=1.9.0
    - readline=7.0
    - regex=2021.4.4
    - requests=2.25.1
    - sacremoses=master
    - send2trash=1.5.0
    - setuptools=52.0.0
    - shellingham=1.4.0
    - sip=4.19.8
    - six=1.15.0
    - smart_open=5.1.0
    - spacy=3.1.1
    - spacy-legacy=3.0.8
    - sqlite=3.33.0
    - srsly=2.4.1
    - statsmodels=0.12.2
    - tensorflow-base=2.0.0
    - thinc=8.0.8
    - tk=8.6.10
    - tokenizers=0.10.1
    - torchaudio=0.7.0
    - torchvision=0.8.1
    - tornado=6.1
    - traitlets=5.0.5
    - transformers=4.4.2
    - typer=0.3.2
    - typing_extensions=3.10.0.0
    - urllib3=1.26.4
    - wasabi=0.8.2
    - wcwidth=0.2.5
    - wheel=0.36.2
    - widgetsnbextension=3.5.1
    - wrapt=1.12.1
    - x264=1!157.20191217
    - xz=5.2.5
    - zeromq=4.3.4
    - zipp=3.4.1
    - zlib=1.2.11
    - zstd=1.4.9